services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kc3-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    environment:
      - TZ=Asia/Tokyo
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kc3-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    environment:
      - TZ=Asia/Tokyo
