name: docker-compose up test

on:
  pull_request:
    branches:
      - develop

jobs:
  test-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start services
        run: docker-compose up -d --build

      - name: Check if services are running
        run: |
          docker-compose ps

      - name: Stop services
        run: docker-compose down
        if: always()
